# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 153b7b970fc8ab7bf273ccc57621aaaf6807e1c5a71075391e3b84761613e77692f72ca634ebe9356a0db944f2295fb299dcb49e42fb5737bac37067d6758555

test:
  secret_key_base: 8ff91dd294f767ff547cacf5c6258f36e8526deb208bacaf7fef978086d2c01d407fab372b32817b579e55c7d0ed472717c0b43020f0e84a449b1ab961d8928f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
